jsxSingleQuote: true
parser: typescript
semi: false
singleQuote: true
trailingComma: all
overrides:
  - files: '*.ts'
    options:
      parser: typescript
  - files: ['*.yml', '*.yaml']
    options:
      parser: yaml
  - files: '*.json'
    options:
      parser: json
      trailingComma: none
  - files: '*.md'
    options:
      parser: markdown
  - files: ['*.css', '*.less', '.scss']
    options:
      parser: css
  - files: ['*.html']
    options:
      parser: html
  - files: ['*.graphql']
    options:
      parser: graphql