import './globals.css'
import { Inter } from 'next/font/google'

import JotaiProvider from '@/components/JotaiProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NFT Gallery',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <JotaiProvider>
        <body className={inter.className}>{children}</body>
      </JotaiProvider>
    </html>
  )
}
